// Sets the browser tab favicon and the "add to home screen" icon to a crisp,
// straight-on render of the app's mascot (CHARACTERS[0], the "icon boy"),
// generated by the same 3D face-render pipeline used for in-app avatars
// (see utils/faceRender.ts + components/FaceIcon.tsx). This keeps the icon in
// perfect visual sync with the character art instead of relying on a
// separately-exported static image that can drift out of date or be a bad
// crop.
import { CHARACTERS } from '../data/characters';
import { getFace } from './faceRender';

function setLinkIcon(rel: string, href: string, sizes?: string) {
  let link = document.querySelector<HTMLLinkElement>(
    sizes ? `link[rel="${rel}"][sizes="${sizes}"]` : `link[rel="${rel}"]`
  );
  if (!link) {
    link = document.createElement('link');
    link.rel = rel;
    if (sizes) link.sizes = sizes;
    document.head.appendChild(link);
  }
  link.href = href;
}

export async function applyMascotAppIcon() {
  try {
    const icon = CHARACTERS[0]; // "Fin" — the mascot used on the landing page
    const dataUrl = await getFace(icon.model, 0.36);
    setLinkIcon('icon', dataUrl);
    setLinkIcon('apple-touch-icon', dataUrl);
  } catch {
    // If the 3D render fails for any reason (slow network, WebGL disabled),
    // silently keep the static fallback declared in index.html.
  }
}
